### ISSUE TITLE
Annoying Background

### ISSUE THREAD

**Issue by dimasrr3** [grasonchan/spotify-spice#10]
![unknown](https://user-images.githubusercontent.com/63847743/160278392-0a6e3a2d-b05b-4b52-a07e-6ab13ff0adb7.png)

hello sir, any fix for this problem? those white background are really annoying me

**Comment by grasonchan** [comment]
@dimasrr3 It has been fixed, try it.

**Comment by dimasrr3** [comment]
umm sorry, but if im using default fulldisplayapp, those disk didnt rotate. and then when im using modified fulldisplayapp it will, but still had those white background
![image](https://user-images.githubusercontent.com/63847743/162664408-8762d4a1-7ce1-4ecb-aa16-a7e76acb934b.png)
this one is default fulldisplay app
![image](https://user-images.githubusercontent.com/63847743/162664444-6db1c816-04c9-4d46-ae44-1f99d6736e3f.png)
and this one with modified fulldisplay app

and if im using both, it will rotate, but there's no button for choosing upcoming and previous song

**Comment by dimasrr3** [comment]
ok im trying reinstall spicetify, 
![image](https://user-images.githubusercontent.com/63847743/162746450-a3a2b979-d2a5-4f84-8255-2a79c95e36ad.png)
it works, but now i should use 2 fulldisplayapp... the original one, and modifier, as you can see, any fix maybe so i can only use 1 instead 2 fulldisplayapp?

**Comment by dimasrr3** [comment]
still exist 
![image](https://user-images.githubusercontent.com/63847743/162747603-b9e8f87e-eaaa-4532-968f-94a64cc866cf.png)

and sometimes the problem's dissapeared, but after using several times and check again, those problem back
im trying to using 2 fulldisplay app, the original and the modified one, the original one didnt had this problem, but those disc didnt rotate.. the modified one is rotating but had those white background, kinda annoying
